[package]
name = "net"
version = "0.1.0"
description = "Networking component of Hilo"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
# Local
hilo-net.workspace = true

# op-alloy
op-alloy-registry.workspace = true

# Workspace
eyre.workspace = true
tracing.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
