[package]
name = "node"
version = "0.1.0"
description = "A Rust implementation of the OP Stack Rollup Node"

edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
repository.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
# Local
hilo-engine.workspace = true
# hilo-net.workspace = true
# hilo = { workspace = true, features = ["registry"] }

# Alloy
op-alloy-genesis.workspace = true
op-alloy-registry.workspace = true

# Workspace
url.workspace = true
eyre.workspace = true
tracing.workspace = true
serde_json = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
metrics-exporter-prometheus = { workspace = true, features = ["http-listener"] }
